# Generated by Django 4.2.16 on 2026-07-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_manager', '0005_yaml_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='yaml',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
