# Generated by Django 4.2.16 on 2026-04-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappintegration',
            name='default_template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
