# Generated by Django 4.2.16 on 2026-07-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_manager', '0005_yaml_elements'),
        ('whatsapp_integration', '0004_seed_platform_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='companywhatsappsettings',
            name='default_invoice_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='yaml_manager.yaml'),
        ),
    ]
