# Generated by Django 4.2.16 on 2026-03-03 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account_number_user_bank_name_user_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_email_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_gst_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state_code',
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_varified', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('company_address', models.CharField(blank=True, max_length=30, null=True)),
                ('company_gst_number', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('state_code', models.IntegerField(blank=True, null=True)),
                ('company_email_id', models.EmailField(blank=True, max_length=30, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='accounts')),
                ('bank_name', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('branch', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=30, null=True)),
                ('subscriptions_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptions')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usercompanies'),
        ),
    ]
