# Generated by Django 4.2.16 on 2026-07-11 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_socialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('permission_type', models.CharField(choices=[('MODEL', 'Model Permission'), ('CUSTOM', 'Custom Business Permission')], default='CUSTOM', max_length=20)),
                ('is_system_permission', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='accounts.usercompanies')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.usercompanies')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.companypermission')),
                ('users', models.ManyToManyField(blank=True, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_groups', to='accounts.usercompanies')),
                ('permissions', models.ManyToManyField(blank=True, related_name='company_groups', to='accounts.companypermission')),
                ('roles', models.ManyToManyField(blank=True, related_name='company_groups', to='accounts.companyrole')),
                ('users', models.ManyToManyField(blank=True, related_name='company_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.usercompanies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserDirectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_user_permissions', to='accounts.usercompanies')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_users', to='accounts.companypermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_direct_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'permission', 'company')},
            },
        ),
        migrations.AddConstraint(
            model_name='companyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('name',), name='uniq_global_role_name'),
        ),
        migrations.AlterUniqueTogether(
            name='companyrole',
            unique_together={('company', 'name')},
        ),
        migrations.AddConstraint(
            model_name='companypermission',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('code',), name='uniq_system_perm_code'),
        ),
        migrations.AlterUniqueTogether(
            name='companypermission',
            unique_together={('code', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='companygroup',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'resource_type', '-timestamp'], name='accounts_au_company_7e7857_idx'),
        ),
    ]
