# Generated by Django 4.2.16 on 2026-07-13 15:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_template_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companygroup',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='companyrole',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='companygroup',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='companyrole',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='companyrole',
            name='uniq_global_role_name',
        ),
        migrations.AlterUniqueTogether(
            name='companygroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='companyrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='companygroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'name'), name='uniq_group_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='companyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'name'), name='uniq_role_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='companyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True), ('is_deleted', False)), fields=('name',), name='uniq_global_role_name'),
        ),
    ]
