"""
Django settings for invoice_api project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(dotenv_path=os.path.join(BASE_DIR, '.env'))

GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')

# --- Razorpay -------------------------------------------------------------
# The .env historically used the bare names `key_id` / `key_secret`, which are
# collision-prone; the namespaced names take precedence when both are present.
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID') or os.environ.get('key_id', '')
RAZORPAY_KEY_SECRET = (os.environ.get('RAZORPAY_KEY_SECRET')
                       or os.environ.get('key_secret', ''))
# Set this to the same value configured at Dashboard → Settings → Webhooks.
# Without it the webhook endpoint refuses every request (503) rather than
# accepting unverified state changes.
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')

# Base URL of the React frontend, used in invite emails
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# ── Environment / security ─────────────────────────────────────────────
#
# Everything below is env-driven and defaults to the SAFE value, so a
# missing variable degrades to "locked down" rather than "wide open".
#
# Required in production .env:
#   DJANGO_DEBUG=False
#   DJANGO_SECRET_KEY=<50+ random chars>
#   DJANGO_ALLOWED_HOSTS=invoice.orvine.in
#   DJANGO_CSRF_TRUSTED_ORIGINS=https://invoice.orvine.in
#   DJANGO_CORS_ALLOWED_ORIGINS=https://invoice.orvine.in


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# Defaults to False: a forgotten env var must not expose tracebacks, settings
# and SQL on a live site.
DEBUG = _env_bool('DJANGO_DEBUG', False)

INSECURE_FALLBACK_KEY = 'django-insecure-ek$w%80pal+0$dygovaza-4fc!fedaex=+(wrl)s_*z3d03$yd'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or INSECURE_FALLBACK_KEY

# SECRET_KEY signs session cookies AND (via SimpleJWT) every access token, so a
# published key means anyone can mint a token for any user. The fallback above
# is committed to git and must never be used off a developer machine.
if not DEBUG and SECRET_KEY == INSECURE_FALLBACK_KEY and 'test' not in sys.argv:
    sys.stderr.write(
        '\n*** SECURITY: DJANGO_SECRET_KEY is not set, so the committed '
        'development key is in use.\n'
        '    It signs session cookies and JWTs — anyone with the repo can '
        'forge a login.\n'
        '    Set DJANGO_SECRET_KEY in .env and restart. Rotating it logs every '
        'user out once.\n\n')

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS') or (
    ['*'] if DEBUG else ['invoice.orvine.in', 'yashadvertisinggroup.com',
                         'api.yashadvertisinggroup.com'])

# Django 4+ requires the scheme here. Missing entries are what produce
# "Origin checking failed - <origin> does not match any trusted origins".
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS') or [
    'https://invoice.orvine.in',
    'https://yashadvertisinggroup.com',
    'https://api.yashadvertisinggroup.com',
    'http://localhost:5173',
    'http://localhost:3000',
    'http://localhost',
]

# ── CORS ──
# `CORS_ALLOW_ALL_ORIGINS` together with `CORS_ALLOW_CREDENTIALS` lets any site
# on the internet call this API with the visitor's cookies attached and read
# the reply. SameSite=Lax on the auth cookie blunts it, but that is one setting
# away from being the only thing standing in the way — so allow-all is now
# confined to DEBUG.
CORS_URLS_REGEX = r'^/api/.*$'
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = _env_list('DJANGO_CORS_ALLOWED_ORIGINS') or [
    'https://invoice.orvine.in',
    'https://yashadvertisinggroup.com',
    'https://api.yashadvertisinggroup.com',
    'http://localhost:3000',
    'http://localhost:5173',
    'http://192.168.29.29:3000',
]
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ORIGIN_ALLOW_ALL = DEBUG

# ── Cookie / transport hardening (HTTPS only) ──
_SECURE_COOKIES = _env_bool('DJANGO_SECURE_COOKIES', not DEBUG)
SESSION_COOKIE_SECURE = _SECURE_COOKIES
CSRF_COOKIE_SECURE = _SECURE_COOKIES
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
# Behind a TLS-terminating proxy, tell Django the original request was HTTPS.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'static'))
STATIC = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'accounts',
    'adminconfig',
    'pdf_builder',
    'companies',
    'invoice',
    'bill_share',
    'yaml_manager',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'inventory',
    'whatsapp_integration',
    'billing',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'invoice_api.middleware.tenant_middleware',  # multi-tenant context (lazy)
]

ROOT_URLCONF = 'invoice_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'invoice_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# ── Cache ──────────────────────────────────────────────────────────────
#
# This MUST be a backend shared by every worker process.
#
# Tenant plan/permission resolution caches its answers (see
# invoice_api/middleware.py) and relies on `cache.delete()` to invalidate
# them when a subscription changes. With Django's default LocMemCache the
# cache is a dict inside a single process, so that delete only reaches the
# one worker that ran it — every other worker keeps serving the old plan
# for up to an hour. The visible symptom is a Pro customer intermittently
# being treated as Free, depending on which worker answers the request.
#
# DatabaseCache is shared by all workers with no extra infrastructure.
# Create its table once per environment:
#
#     python manage.py createcachetable
#
# If Redis becomes available, swap BACKEND for
# 'django.core.cache.backends.redis.RedisCache' with LOCATION set to the
# Redis URL — nothing else needs to change.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache',
        'TIMEOUT': 300,
        'OPTIONS': {
            # tenant caches are small; keep well clear of the cull threshold
            'MAX_ENTRIES': 10000,
            'CULL_FREQUENCY': 4,
        },
    },
}

# The test suite calls cache.clear() between cases and must not depend on a
# cache table existing.
if 'test' in sys.argv:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'
APPEND_SLASH = False
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=50),  # by default
    'REFRESH_TOKEN_LIFETIME': timedelta(days=50),  # by default
    'UPDATE_LAST_LOGIN': True,
    'AUTH_TOKEN_CLASSES': (
        'rest_framework_simplejwt.tokens.AccessToken', 'rest_framework_simplejwt.tokens.RefreshToken',),
    'AUTH_COOKIE': 'access_token',  # Cookie name. Enables cookies if value is set.
    'AUTH_COOKIE_DOMAIN': None,  # A string like "example.com", or None for standard domain cookie.
    # Follows DEBUG: on an HTTPS site the auth cookie must never be allowed
    # out over plain HTTP, or a downgraded request leaks the session.
    'AUTH_COOKIE_SECURE': _SECURE_COOKIES,
    'AUTH_COOKIE_HTTP_ONLY': True,  # Http only cookie flag.It's not fetch by javascript.
    'AUTH_COOKIE_PATH': '/',  # The path of the auth cookie.
    'AUTH_COOKIE_SAMESITE': 'Lax',
    # Whether to set the flag restricting cookie leaks on cross-site requests. This can be 'Lax', 'Strict', or None to disable the flag.

}

IS_TESTING = 'test' in sys.argv  # `sys` imported at the top of this module

REST_FRAMEWORK = {
    # 'DEFAULT_PAGINATION_CLASS': ['rest_framework.pagination.PageNumberPagination'],
    'PAGE_SIZE': 20,
    'SEARCH_PARAM': 's',
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'EXCEPTION_HANDLER': 'invoice_api.exceptions.api_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authenticate.CustomAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [] if IS_TESTING else [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    'DEFAULT_THROTTLE_RATES': {

        'anon': '5/min',

        'user': '200/min'

    }

}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',  # Change to WARNING or ERROR to reduce noise
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django.log'),  # Log file location
            'formatter': 'simple',
        },
        'Info': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django_info.log'),  # Log file location
            'formatter': 'simple',
        },
    },
    'loggers': {
        "invoice": {
            "handlers": ["console", "file","Info"],
            "level": "DEBUG",  # you can set different level
            "propagate": False,
        },
        "accounts": {
            "handlers": ["console", "file","Info"],
            "level": "DEBUG",  # you can set different level
            "propagate": False,
        },
        "billing": {
            "handlers": ["console", "file", "Info"],
            "level": "INFO",
            "propagate": False,
        },
        # Add filters if needed
    },
}
# https://docs.djangoproject.com/en/stable/topics/email/
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')  # Your email address
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')  # Your email app password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
INVOICE_CONVERTOR_PIPLINE_URL = os.environ.get('INVOICE_CONVERTOR_PIPLINE_URL','http://localhost:8001')
