# Generated by Django 5.0 on 2024-02-10 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='new_product_in_frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_title', models.CharField(blank=True, max_length=30)),
                ('size', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_show', models.BooleanField(default=False)),
                ('is_calculable', models.BooleanField(default=False)),
                ('formula', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('new_product_in_frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.new_product_in_frontend')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30)),
                ('receiver', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('gst_final_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_final_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='invoice.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('new_product_in_frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.new_product_in_frontend')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_properties',
            field=models.ManyToManyField(to='invoice.product_properties'),
        ),
    ]
