# Generated by Django 5.0 on 2024-02-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='gst_final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(blank=True, to='invoice.product'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
