# Generated by Django 5.0 on 2024-02-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_product_new_product_in_frontend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
    ]
