# Generated by Django 5.0 on 2024-02-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='invoice.product'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receiver',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
