# Generated by Django 5.0 on 2024-02-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_date_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_properties',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
