# Generated by Django 4.2.16 on 2026-07-13 15:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_payment_creditdebitnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='new_product_in_frontend',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='customfield',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='new_product_in_frontend',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='customfield',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='new_product_in_frontend',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new_product_in_frontend',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
