# Generated by Django 4.2.16 on 2026-03-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companies_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Company', max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', help_text='As per GST/PAN records', max_length=255)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('website', models.URLField(blank=True, default=None, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=3000)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('state_code', models.IntegerField(blank=True, default=None, help_text='GST State Code', null=True)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('gst_number', models.CharField(blank=True, default='', help_text='GSTIN (15 characters)', max_length=15)),
                ('pan_number', models.CharField(blank=True, default='', max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=30)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=11)),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('incorporation_date', models.DateField(blank=True, default=None, null=True)),
                ('business_type', models.CharField(choices=[('private_limited', 'Private Limited'), ('public_limited', 'Public Limited'), ('partnership', 'Partnership'), ('sole_prop', 'Sole Proprietorship'), ('llp', 'LLP'), ('ngo', 'NGO'), ('other', 'Other')], default='sole_prop', max_length=50)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companies',
            name='user',
        ),
    ]
