# Generated by Django 4.2.16 on 2026-05-07 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_delete_companies_customers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Vendor', max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', help_text='As per GST/PAN records', max_length=255)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('website', models.URLField(blank=True, default=None, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=3000)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('state_code', models.IntegerField(blank=True, default=None, help_text='GST State Code', null=True)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('gst_number', models.CharField(blank=True, default='', help_text='GSTIN (15 characters)', max_length=15)),
                ('pan_number', models.CharField(blank=True, default='', max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=30)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=11)),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('business_type', models.CharField(choices=[('private_limited', 'Private Limited'), ('public_limited', 'Public Limited'), ('partnership', 'Partnership'), ('sole_prop', 'Sole Proprietorship'), ('llp', 'LLP'), ('ngo', 'NGO'), ('other', 'Other')], default='sole_prop', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
